--Data

--T_TYPES
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('100', 'QPSQL', 'BOOLEAN', 'Boolean', null, null, 'boolean');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('101', 'QPSQL', 'SMALLINT', 'SmallInt', null, null, 'integer');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('102', 'QPSQL', 'INTEGER', 'Integer', null, null, 'integer');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('103', 'QPSQL', 'BIGINT', 'BigInt', null, null, 'integer');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('104', 'QPSQL', 'DATE', 'Date', null, null, 'date');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('105', 'QPSQL', 'TIMESTAMP', 'Timestamp', null, null, 'datetime');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('106', 'QPSQL', 'CHARACTER VARYING', 'Varchar', null, null, 'string');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('107', 'QPSQL', 'TIME', 'Time', null, null, 'time');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('108', 'QPSQL', 'REAL', 'Real', null, null, 'decimal');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('109', 'QPSQL', 'CHAR', 'Char', null, null, 'string');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('110', 'QPSQL', 'NUMERIC', 'Numeric', null, null, 'decimal');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('111', 'QPSQL', 'UUID', 'UUID', null, null, 'string');


--T_FUNCTIONS
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1002', 'abs', '[integer|smallint|numeric|real]', 'absolute value', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1003', 'cbrt', '[dp]', 'cube root', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1004', 'ceil', '[dp|numeric]', 'nearest integer greater than or equal to argument', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1005', 'ceiling', '[dp|numeric]', 'nearest integer greater than or equal to argument ', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1006', 'degrees', '[dp]', 'radians to degrees', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1007', 'div', '[numeric],[numeric]', 'integer quotient of y/x', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1008', 'exp', '[dp|numeric]', 'exponential', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1009', 'floor', '[dp|numeric]', 'nearest integer less than or equal to argument', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1010', 'ln', '[dp|numeric]', 'natural logarithm', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1011', 'log', '[dp|numeric]', 'base 10 logarithm', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1012', 'log', '[b numeric, x numeric]', 'logarithm to base b', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1013', 'mod', '[y],[x]', 'remainder of y/x', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1014', 'pi', '', '"π" constant', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1015', 'power', '[a dp, b dp]', 'a raised to the power of b', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1016', 'radians', '[dp]', ' 	degrees to radians', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1017', 'round', '[dp|numeric]', 'round to nearest integer', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1018', 'sign', 'dp|numeric', 'sign of the argument (-1, 0, +1)', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1019', 'sqrt', 'dp|numeric', 'square root', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1020', 'trunc', 'dp|numeric', 'truncate toward zero', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1021', 'random', '', 'random value in the range 0.0 <= x < 1.0', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1022', 'acos', '[x]', 'inverse cosine', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1023', 'asin', '[x]', 'inverse sine', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1024', 'atan', '[x]', 'inverse tangent', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1025', 'atan2', '[y],[x]', 'inverse tangent of y/x', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1026', 'cos', '[x]', 'cosine', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1027', 'cot', '[x]', 'cotangent', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1028', 'sin', '[x]', 'sine', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1029', 'tan', '[x]', 'tangent', 'https://www.postgresql.org/docs/14/functions-math.html', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1030', 'bit_length', '', 'Number of bits in string', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1031', 'char_length', '', 'Number of characters in string', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1032', 'lower', '[string]', 'Convert string to lower case', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1033', 'octet_length', '', 'Number of bytes in string', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1034', 'overlay', '', 'Replace substring', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1035', 'position', '', 'Location of specified substring', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1036', 'substring', '', 'Extract substring', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1037', 'trim', '[string]', 'Remove the longest string containing only characters from characters', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1038', 'upper', '[string]', 'Convert string to upper case', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1039', 'length', '[string]', 'Number of characters in string', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1040', 'md5', '[string]', 'Calculates the MD5 hash of string, returning the result in hexadecimal', NULL, 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1041', 'regexp_matches', '', 'Return all captured substrings resulting from matching a POSIX regular expression against the string. ', NULL, 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1042', 'regexp_replace', '', 'Replace substring(s) matching a POSIX regular expression. ', NULL, 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1043', 'repeat', '', 'Repeat string the specified number of times', NULL, 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1044', 'replace', '', 'Replace all occurrences in string of substring from with substring to', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1045', 'reverse', '[string]', 'Return reversed string.', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1046', 'left', '[string]', 'Return first n characters in the string. When n is negative, return all but last |n| characters.', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1047', 'right', '[string]', 'Return last n characters in the string. When n is negative, return all but first |n| characters.', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1048', 'ltrim', '[string]', 'Remove the longest string containing only characters from characters (a space by default) from the start of string', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('1049', 'rtrim', '[string]', 'Remove the longest string containing only characters from characters (a space by default) from the end of string', 'https://www.postgresql.org/docs/14/functions-string.html#FUNCTIONS-STRING-SQL', 'QPSQL');

--T_KEYWORDS
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('101', 'select', 'select - is a basic SQL keyword', 'https://www.postgresql.org/docs/14/sql-select.html', 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('102', 'from', '<b>FROM</b> - is a very good word', NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('103', 'where', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('104', 'order', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('105', 'insert', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('106', 'update', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('107', 'delete', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('108', 'create', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('109', 'drop', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('110', 'table', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('111', 'view', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('112', 'index', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('113', 'by', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('114', 'and', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('115', 'or', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('116', 'in', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('117', 'into', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('118', 'case', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('119', 'coalesce', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('120', 'count', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('121', 'alter', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('122', 'left', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('123', 'join', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('124', 'right', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('125', 'inner', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('126', 'for', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('127', 'like', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('128', 'min', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('129', 'max', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('130', 'exists', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('131', 'set', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('132', 'sum', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('133', 'with', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('134', 'lock', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('135', 'having', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('136', 'outer', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('137', 'trim', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('138', 'trigger', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('139', 'procedure', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('140', 'sequence', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('141', 'column', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('142', 'add', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('143', 'null', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('144', 'constraint', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('145', 'unique', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('146', 'not', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('147', 'then', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('148', 'end', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('149', 'on', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('150', 'full', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('151', 'asc', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('152', 'ascending', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('153', 'desc', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('154', 'descending', NULL, NULL, 'QPSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('155', 'distinct', NULL, NULL, 'QPSQL');