--Data

--T_TYPES
insert into t_types ("id", "dbms", "name", "caption") values ('200', 'QMYSQL', 'CHAR', 'Char');
insert into t_types ("id", "dbms", "name", "caption") values ('201', 'QMYSQL', 'VARCHAR', 'Varchar');
insert into t_types ("id", "dbms", "name", "caption") values ('202', 'QMYSQL', 'TINYTEXT', 'Tiny Text');
insert into t_types ("id", "dbms", "name", "caption") values ('203', 'QMYSQL', 'TEXT', 'Text');
insert into t_types ("id", "dbms", "name", "caption") values ('204', 'QMYSQL', 'MEDIUMTEXT', 'Medium Text');
insert into t_types ("id", "dbms", "name", "caption") values ('205', 'QMYSQL', 'LARGETEXT', 'Large Text');
insert into t_types ("id", "dbms", "name", "caption") values ('206', 'QMYSQL', 'TINYINT', 'Tiny Int');
insert into t_types ("id", "dbms", "name", "caption") values ('207', 'QMYSQL', 'BOOL', 'Bool');
insert into t_types ("id", "dbms", "name", "caption") values ('208', 'QMYSQL', 'SMALLINT', 'Small Int');
insert into t_types ("id", "dbms", "name", "caption") values ('209', 'QMYSQL', 'MEDIUMINT', 'Medium Int');
insert into t_types ("id", "dbms", "name", "caption") values ('210', 'QMYSQL', 'INT', 'Int');
insert into t_types ("id", "dbms", "name", "caption") values ('211', 'QMYSQL', 'BIGINT', 'Bigint');
insert into t_types ("id", "dbms", "name", "caption") values ('212', 'QMYSQL', 'DECIMAL', 'Decimal');
insert into t_types ("id", "dbms", "name", "caption") values ('213', 'QMYSQL', 'FLOAT', 'Float');
insert into t_types ("id", "dbms", "name", "caption") values ('214', 'QMYSQL', 'DOUBLE', 'Double');
insert into t_types ("id", "dbms", "name", "caption") values ('215', 'QMYSQL', 'DATE', 'Date');
insert into t_types ("id", "dbms", "name", "caption") values ('216', 'QMYSQL', 'TIME', 'Time');
insert into t_types ("id", "dbms", "name", "caption") values ('217', 'QMYSQL', 'DATETIME', 'Date/Time');
insert into t_types ("id", "dbms", "name", "caption") values ('218', 'QMYSQL', 'TIMESTAMP', 'Timestamp');
insert into t_types ("id", "dbms", "name", "caption") values ('219', 'QMYSQL', 'YEAR', 'Year');
insert into t_types ("id", "dbms", "name", "caption") values ('220', 'QMYSQL', 'ENUM', 'Enum');
insert into t_types ("id", "dbms", "name", "caption") values ('221', 'QMYSQL', 'SET', 'Set');
insert into t_types ("id", "dbms", "name", "caption") values ('222', 'QMYSQL', 'TINYBLOB', 'Tiny Blob');
insert into t_types ("id", "dbms", "name", "caption") values ('223', 'QMYSQL', 'BLOB', 'Blob');
insert into t_types ("id", "dbms", "name", "caption") values ('224', 'QMYSQL', 'MEDIUMBLOB', 'Medium Blob');
insert into t_types ("id", "dbms", "name", "caption") values ('225', 'QMYSQL', 'LARGEBLOB', 'Large Blob');

--T_KEYWORDS
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('201', 'select', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('202', 'from', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('203', 'where', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('204', 'order', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('205', 'insert', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('206', 'update', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('207', 'delete', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('208', 'create', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('209', 'drop', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('210', 'table', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('211', 'view', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('212', 'index', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('213', 'by', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('214', 'and', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('215', 'or', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('216', 'in', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('217', 'into', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('218', 'case', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('219', 'coalesce', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('220', 'count', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('221', 'alter', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('222', 'left', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('223', 'join', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('224', 'right', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('225', 'inner', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('226', 'for', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('227', 'like', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('228', 'min', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('229', 'max', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('230', 'exists', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('231', 'set', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('232', 'sum', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('233', 'with', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('234', 'lock', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('235', 'having', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('236', 'outer', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('237', 'trim', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('238', 'trigger', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('239', 'procedure', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('240', 'sequence', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('241', 'column', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('242', 'add', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('243', 'null', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('244', 'constraint', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('245', 'unique', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('246', 'not', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('247', 'then', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('248', 'end', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('249', 'on', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('250', 'full', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('251', 'asc', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('252', 'ascending', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('253', 'desc', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('254', 'descending', NULL, NULL, 'QMYSQL');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('255', 'distinct', NULL, NULL, 'QMYSQL');
