--Data

--T_TYPES
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('300', 'QSQLITE', 'INTEGER', 'Integer', null, null, 'integer');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('301', 'QSQLITE', 'TEXT', 'Text', null, null, 'string');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('302', 'QSQLITE', 'REAL', 'Real', null, null, 'decimal');
insert into t_types ("id", "driver", "name", "caption", "description", "doclink", "kind") values ('303', 'QSQLITE', 'BLOB', 'Blob', null, null, 'blob');

--T_FUNCTIONS
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3000', 'abs', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3001', 'changes', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3002', 'char', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3003', 'coalesce', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3004', 'format', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3005', 'glob', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3006', 'hex', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3007', 'ifnull', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3008', 'iif', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3009', 'instr', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3010', 'last_insert_rowid', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3011', 'length', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3012', 'like', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3013', 'likelihood', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3014', 'likely', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3015', 'load_extension', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3016', 'lower', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3017', 'ltrim', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3018', 'max', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3019', 'min', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3020', 'nullif', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3021', 'printf', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3022', 'quote', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3023', 'random', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3024', 'randomblob', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3025', 'replace', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3026', 'round', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3027', 'rtrim', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3028', 'sign', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3029', 'soundex', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3030', 'sqlite_compileoption_get', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3031', 'sqlite_compileoption_used', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3032', 'sqlite_offset', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3033', 'sqlite_source_id', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3034', 'sqlite_version', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3035', 'substr', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3036', 'substring', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3037', 'total_changes', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3038', 'trim', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3039', 'typeof', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3040', 'unicode', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3041', 'unlikely', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3042', 'upper', '', '', NULL, 'QSQLITE');
insert into t_functions ("id", "name", "args", "description", "doclink", "driver") values ('3043', 'zeroblob', '', '', NULL, 'QSQLITE');


--T_KEYWORDS
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('301', 'select', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('302', 'from', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('303', 'where', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('304', 'order', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('305', 'insert', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('306', 'update', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('307', 'delete', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('308', 'create', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('309', 'drop', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('310', 'table', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('311', 'view', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('312', 'index', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('313', 'by', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('314', 'and', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('315', 'or', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('316', 'in', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('317', 'into', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('318', 'case', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('319', 'coalesce', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('320', 'count', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('321', 'alter', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('322', 'left', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('323', 'join', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('324', 'right', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('325', 'inner', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('326', 'for', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('327', 'like', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('328', 'min', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('329', 'max', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('330', 'exists', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('331', 'set', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('332', 'sum', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('333', 'with', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('334', 'lock', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('335', 'having', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('336', 'outer', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('337', 'trim', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('338', 'trigger', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('339', 'procedure', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('340', 'sequence', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('341', 'column', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('342', 'add', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('343', 'null', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('344', 'constraint', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('345', 'unique', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('346', 'not', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('347', 'then', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('348', 'end', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('349', 'on', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('350', 'full', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('351', 'asc', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('352', 'ascending', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('353', 'desc', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('354', 'descending', NULL, NULL, 'QSQLITE');
insert into t_keywords ("id", "name", "description", "doclink", "driver") values ('355', 'distinct', NULL, NULL, 'QSQLITE');