#ifndef APPCONST_H
#define APPCONST_H

#define F_NAME "name"
#define F_CAPTION "caption"
#define F_QUERY_TEXT "queryText"
#define F_ID "id"
#define F_HOSTNAME "hostName"
#define F_USERNAME "userName"
#define F_PASSWORD "password"
#define F_DRIVER_NAME "driverName"
#define F_DATABASE_NAME "databaseName"
#define F_KEYWORD "keyword"
#define F_CURRENT_VALUE "currentValue"
#define F_MIN_VALUE "minValue"
#define F_MAX_VALUE "maxValue"
#define F_STEP "step"
#define F_START_VALUE "startValue"
#define F_SOURCE_CODE "sourceCode"
#define F_LANGUAGE "language"
#define F_RETURN_TYPE "returnType"
#define F_DBMS "dbms"

#define F_EVENT_INSERT "eventInsert"
#define F_EVENT_UPDATE "eventUpdate"
#define F_EVENT_DELETE "eventDelete"
#define F_EVENT_TRUNCATE "eventTruncate"
#define F_TIMING "timing"
#define F_TABLE "table"
#define F_COLUMN "column"
#define F_REFTABLE "reftable"
#define F_REFCOLUMN "refcolumn"
#define F_ON_UPDATE "onUpdate"
#define F_ON_DELETE "onDelete"
#define F_FUNCTION "function"
#define F_ENABLED "enabled"

#define F_SIZE "size"
#define F_NULL "null"
#define F_PK "pk"
#define F_UNIQUE "unique"
#define F_TYPE "type"

#define OBJTYPE_TABLE "table"
#define OBJTYPE_VIEW "view"
#define OBJTYPE_SEQUENCE "sequence"
#define OBJTYPE_TRIGGER "trigger"
#define OBJTYPE_PROCEDURE "procedure"

#define FOLDER_TABLES "tables"
#define FOLDER_PROCEDURES "procedures"
#define FOLDER_VIEWS "views"
#define FOLDER_SEQUENCES "sequences"
#define FOLDER_TRIGGERS "triggers"
#define FOLDER_SYSTABLES "systables"
//#define OBJTYPE_

#define T_KEYWORDS "t_keywords"
#define T_DATABASE "t_database"
#define T_TYPES "t_types"

#define DEF_DATABASE_NAME "New database"
#define DEF_VIEW_NAME "NewView"
#define DEF_TABLE_NAME "NewTable"
#define DEF_SEQUENCE_NAME "NewSequence"
#define DEF_TRIGGER_NAME "NewTrigger"
#define DEF_PROCEDURE_NAME "NewProcedure"
#define DEF_COLUMN_NAME "NewColumn"

#define TITLE_ERROR "Error"
#define TITLE_WARNING "Warning"
#define TITLE_INFO "Information"

#define DRIVER_SQLITE "QSQLITE"
#define DRIVER_MYSQL "QMYSQL"
#define DRIVER_PSQL "QPSQL"
#define DRIVER_FIREBIRD "QIBASE"

#endif // APPCONST_H
